language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.4
  - 2.3.0
  - ruby-head

before_install:
  - "gem install bundler" # -v 1.7.14 if a specific version is needed